branch:
  only: master
language: cpp
sudo: required
matrix:
  include:
    - os: osx
      osx-image: xcode8
    - os: osx
      osx-image: xcode8.3
    - os: osx
      osx-image: xcode9
    - os: osx
      osx-image: xcode9.4

addons:
  homebrew:
    packages:
      - cmake

install:
  - cmake --version

script:
